FROM registry.access.redhat.com/ubi9/nodejs-20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-124
COPY --from=builder /app/dist /usr/share/nginx/html
USER 1001
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
