apiVersion: v1
kind: ConfigMap
metadata:
  name: lam-config
  namespace: ldap-lab
data:
  lam.conf: |
    {
      "Passwd": "{SSHA}rGisy6/ZgTO+5sVP+hs5VCkwh8M= UcXSSA==",
      "ServerURL": "ldap://dirsrv-internal.ldap-lab.svc.cluster.local:3389",
      "useTLS": "no",
      "followReferrals": "false",
      "pagedResults": "false",
      "Admins": "cn=Directory Manager",
      "defaultLanguage": "en_US.utf8",
      "scriptPath": "",
      "scriptServer": "",
      "scriptRights": "750",
      "serverDisplayName": "BANCO LDAP",
      "activeTypes": "user,group",
      "accessLevel": "100",
      "loginMethod": "list",
      "loginSearchSuffix": "ou=USUARIOS,o=BANCO",
      "loginSearchFilter": "cn=%USER%",
      "searchLimit": "0",
      "lamProMailFrom": "noreply@example.com",
      "lamProMailReplyTo": "",
      "lamProMailSubject": "Your password was reset",
      "lamProMailText": "Dear @@givenName@@ @@sn@@,+::++::+your password was reset to: @@newPassword@@+::++::++::+Best regards+::++::+deskside support+::+",
      "lamProMailIsHTML": "false",
      "lamProMailAllowAlternateAddress": "true",
      "httpAuthentication": "false",
      "loginSearchDN": "",
      "loginSearchPassword": "",
      "timeZone": "America/Sao_Paulo",
      "jobsBindUser": null,
      "jobsBindPassword": null,
      "jobsDatabase": null,
      "jobsDBHost": null,
      "jobsDBPort": null,
      "jobsDBUser": null,
      "jobsDBPassword": null,
      "jobsDBName": null,
      "pwdResetAllowSpecificPassword": "true",
      "pwdResetAllowScreenPassword": "true",
      "pwdResetForcePasswordChange": "true",
      "pwdResetDefaultPasswordOutput": "2",
      "scriptUserName": "",
      "scriptSSHKey": "",
      "scriptSSHKeyPassword": "",
      "twoFactorAuthentication": "none",
      "twoFactorAuthenticationURL": "https://localhost",
      "twoFactorAuthenticationInsecure": false,
      "twoFactorAuthenticationLabel": "",
      "twoFactorAuthenticationOptional": false,
      "twoFactorAuthenticationCaption": "",
      "twoFactorAuthenticationClientId": "",
      "twoFactorAuthenticationSecretKey": "",
      "twoFactorAuthenticationDomain": "",
      "twoFactorAuthenticationAttribute": "cn",
      "twoFactorAllowToRememberDevice": "false",
      "twoFactorRememberDeviceDuration": "28800",
      "twoFactorRememberDevicePassword": "uZ0TJJUrHtUO6VcVFouw9zlk0zMRtV",
      "referentialIntegrityOverlay": "false",
      "hidePasswordPromptForExpiredPasswords": "false",
      "hideDnPart": "",
      "pwdPolicyMinLength": "",
      "pwdPolicyMinLowercase": "",
      "pwdPolicyMinUppercase": "",
      "pwdPolicyMinNumeric": "",
      "pwdPolicyMinSymbolic": "",
      "typeSettings": {
        "suffix_user": "ou=USUARIOS,o=BANCO",
        "attr_user": "#cn;#sn;#description",
        "modules_user": "inetOrgPerson",
        "suffix_group": "ou=TRANCODES,ou=CBV,ou=APLICACOES,o=BANCO",
        "attr_group": "#cn;#member;#description",
        "modules_group": "groupOfNames"
      },
      "moduleSettings": {},
      "toolSettings": {
        "treeViewSuffix": "o=BANCO",
        "tool_hide_toolServerInformation": "false",
        "tool_hide_toolFileUpload": "false",
        "tool_hide_toolMultiEdit": "false",
        "tool_hide_toolPDFEditor": "false",
        "tool_hide_toolOUEditor": "false",
        "tool_hide_toolProfileEditor": "false",
        "tool_hide_ImportExport": "false",
        "tool_hide_toolWebauthn": "false",
        "tool_hide_toolSchemaBrowser": "false",
        "tool_hide_TreeViewTool": "false",
        "tool_hide_toolTests": "false"
      }
    }