quarkus.http.port=8080

quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=resource_access/cbv-client/roles


quarkus.kubernetes.deployment-target=openshift
quarkus.kubernetes.namespace=rhbk-apps
quarkus.openshift.route.expose=true
quarkus.openshift.build-strategy=binary
quarkus.s2i.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17:latest
quarkus.container-image.build=true

quarkus.openshift.env.vars."OIDC_AUTH_SERVER_URL"=${OIDC_AUTH_SERVER_URL}
quarkus.openshift.env.vars."OIDC_CLIENT_ID"=${OIDC_CLIENT_ID}